"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { PropsWithChildren } from "react";

import { Button } from "@/components/ui/button";
import { homeNavConfig } from "@/config/home-nav.config";
import { cn } from "@/lib/utils";

/**
 * Stable shell for `/home/**`. Renders persistent header actions (create CTAs) and an optional
 * sub-nav rail above the page body. Both are driven by `src/config/home-nav.config.ts`, which
 * is the additive extension point ARIA codegen writes to during MVP build.
 *
 * **Do not edit this file** — it is on `mandatoryDoNotModifyPaths`. To add nav surfaces, write
 * to `home-nav.config.ts` instead.
 *
 * Behavioral guarantees:
 *   - Header actions render with the SAME visibility regardless of page state (empty/populated).
 *     Empty-state illustrations on a child page can re-render the same CTA at a larger size, but
 *     the header CTA is always present.
 *   - Sub-nav highlights the active route via `usePathname().startsWith(href)` (or exact match
 *     for `/home`).
 *   - The shell is fully optional: when both arrays are empty, only `children` renders — the
 *     bare template behaves identically to before.
 */
export function HomeShell({ children }: PropsWithChildren) {
  const pathname = usePathname();
  const { homeHeaderActions, homeSubNav } = homeNavConfig;

  const hasHeader = homeHeaderActions.length > 0;
  const hasSubNav = homeSubNav.length > 0;
  const showShell = hasHeader || hasSubNav;

  if (!showShell) {
    return <>{children}</>;
  }

  return (
    <div className="space-y-4">
      {hasHeader ? (
        <header
          className="flex flex-wrap items-center justify-end gap-2"
          aria-label="Home header actions"
        >
          {homeHeaderActions.map((action) => (
            <Button
              key={`${action.label}:${action.href}`}
              type="button"
              size="sm"
              render={<Link href={action.href} />}
            >
              {action.label}
            </Button>
          ))}
        </header>
      ) : null}

      {hasSubNav ? (
        <nav
          aria-label="Home sub-navigation"
          className="flex flex-wrap items-center gap-1 border-b text-sm"
        >
          {homeSubNav.map((item) => {
            const isActive =
              item.href === "/home"
                ? pathname === "/home"
                : pathname === item.href || pathname.startsWith(`${item.href}/`);
            return (
              <Link
                key={item.href}
                href={item.href}
                className={cn(
                  "-mb-px border-b-2 px-3 py-2 text-muted-foreground transition-colors hover:text-foreground",
                  isActive
                    ? "border-primary text-foreground"
                    : "border-transparent"
                )}
              >
                {item.label}
              </Link>
            );
          })}
        </nav>
      ) : null}

      <div>{children}</div>
    </div>
  );
}
