"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { type PropsWithChildren } from "react";

import { extraSettingsTabs } from "@/config/settings-tabs.config";
import { cn } from "@/lib/utils";

/**
 * Wraps every route under `/settings/**` with a header + tab strip. Each tab links to
 * `/settings/<slug>`. The "Profile" tab is built-in and always rendered first; extras come from
 * `src/config/settings-tabs.config.ts`.
 *
 * Hoisting this into `(app)/settings/layout.tsx` (rather than per-page) means: when the user
 * navigates between tabs, the shell stays mounted and the header doesn't flicker — and a tab
 * the user sees on `/settings` is still visible after they click into `/settings/api-keys`.
 *
 * Do not edit this file. Add new tabs by writing to `src/config/settings-tabs.config.ts` and
 * creating the corresponding `src/app/(app)/settings/<slug>/page.tsx`.
 */
export function SettingsShell({ children }: PropsWithChildren) {
  const pathname = usePathname() ?? "/settings";

  const tabs = [
    { href: "/settings", label: "Profile", isActive: pathname === "/settings" },
    ...extraSettingsTabs.map((tab) => {
      const slug = tab.slug.replace(/^\/+|\/+$/g, "");
      const href = `/settings/${slug}`;
      return { href, label: tab.label, isActive: pathname.startsWith(href) };
    }),
  ];

  const showTabStrip = tabs.length > 1;

  return (
    <section className="space-y-6">
      <header className="space-y-1">
        <h1 className="text-2xl font-semibold tracking-tight">Settings</h1>
        <p className="text-sm text-muted-foreground">
          Manage your account and application preferences.
        </p>
      </header>

      {showTabStrip ? (
        <nav
          aria-label="Settings sections"
          className="flex flex-wrap items-center gap-1 border-b"
        >
          {tabs.map((tab) => (
            <Link
              key={tab.href}
              href={tab.href}
              aria-current={tab.isActive ? "page" : undefined}
              className={cn(
                "-mb-px border-b-2 px-3 py-2 text-sm transition-colors",
                tab.isActive
                  ? "border-primary text-foreground"
                  : "border-transparent text-muted-foreground hover:text-foreground"
              )}
            >
              {tab.label}
            </Link>
          ))}
        </nav>
      ) : null}

      <div>{children}</div>
    </section>
  );
}
