import { canUserRunProtectedAction } from "@/lib/server/billing/gating";

import { ApiError } from "./api-error";

/**
 * Throws `ApiError("subscription_required_for_action", 402)` when the user does NOT have an
 * active-ish subscription AND the build config requires one for protected actions.
 *
 * Generated MVPs MUST call this on every API route that the spec's
 * `capabilities.paywallGating.gatedRoutes` lists. The `audit-paywall` audit fails the build for
 * gated routes that don't import + call this helper.
 *
 * Behavior matches the existing `gating.canUserRunProtectedAction`:
 *   - `monetizationMode === "paid_only"` always requires active subscription.
 *   - `gating.requireActiveSubscriptionForProtectedActions === true` also requires it.
 *   - Otherwise no-op (the call is allowed).
 *
 * Do not edit this file.
 */
export async function requireActiveSubscription(userId: string): Promise<void> {
  const allowed = await canUserRunProtectedAction(userId);
  if (!allowed) {
    throw new ApiError("subscription_required_for_action", 402);
  }
}
